### ISSUE TITLE
Compile error?

### ISSUE THREAD

**Issue by woodoo46** [lbcb-sci/graphmap2#9]
I downloaded graphmap2-0.6.3, and tried to compile it, I got this error:

In file included from src/aligner/anchor_aligner.h:13:0,
                 from src/aligner/anchor_aligner.cc:8:
./src/containers/results.h:14:37: fatal error: utility/utility_general.h: No such file or directory
compilation terminated.
make: *** [obj_linux/src/aligner/anchor_aligner.o] Error 1

**Comment by jmaricb** [comment]
Hi. I just tried to clone and build the repository and it worked. Can you tell me how did you try to compile the code. What were the steps? Did you run:
git clone https://github.com/lbcb-sci/graphmap2  
cd graphmap2  
make modules  
make

**Comment by woodoo46** [comment]
I downloaded graphmap2-0.6.3.zip, and 
unzip graphmap2-0.6.3.zip
cd graphmap2-0.6.3
make
Then, I got the error.

**Comment by jmaricb** [comment]
That is because you didn't pull the modules that are being used. You are missing 'make modules' command. Can you try the steps I have put in the previous post? If not, I will see how to run it by donwloading zip.

**Comment by woodoo46** [comment]
Ya. It worked when I followed your steps.
